global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'

route:
  receiver: "abc"
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 1m

receivers:
- name: "abc"
  webhook_configs:
  - url: 'http://abc:8080'
    send_resolved: true
    http_config:
      basic_auth:
        username: admin@abc.io
        password: abc