global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'

route:
  receiver: "slack_general"
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 15s

receivers:
- name: "amixr"
  webhook_configs:
  - send_resolved: true
    url: https://app.amixr.io/integrations/v1/alertmanager/123/

- name: "slack_general"
  slack_configs:
  - api_url: https://hooks.slack.com/services/123
    channel: '#general'
