global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "prometheus.rules.yml"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'webserver'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['webserver:8000']

  - job_name: 'machine-vm'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'metrics-gateway'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['metrics-gateway:9091']

  - job_name: 'node-exporter'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['206.189.75.110:9100','206.189.75.71:9100','206.189.170.125:9100','167.172.119.0:9100','167.172.123.223:9100','206.189.172.103:9100','167.172.119.21:9100','206.189.79.197:9100','167.172.123.245:9100','167.172.119.54:9100']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
