global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "prometheus.rules.yml"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'webserver'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['webserver:8000']

  - job_name: 'machine-vm'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'metrics-gateway'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['metrics-gateway:9091']

  - job_name: 'node-exporter'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['167.172.220.208:9100','159.65.100.178:9100','159.65.104.42:9100','159.65.102.125:9100','159.65.107.79:9100','167.172.219.32:9100','167.172.213.34:9100','167.172.209.238:9100','167.99.108.163:9100','167.172.210.249:9100']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
